export const inboxPage = `<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>スタックチャンへ伝言</title><style>body{font:18px system-ui;background:#f7f5ef;color:#25372f;max-width:540px;margin:3rem auto;padding:1rem}input,button,select{font:inherit;padding:.7rem;border:1px solid #88958a;border-radius:10px;box-sizing:border-box;max-width:100%}label{display:grid;gap:.4rem;margin:1rem 0}button{background:#245f48;color:white;cursor:pointer}section{background:white;padding:1rem;border-radius:16px;margin:1rem 0}p{line-height:1.7}li{margin:.8rem 0}</style>
<h1>スタックチャンへ伝言</h1><p>同じLANの本体で「伝言箱 → 送信者を登録」を開き、表示されたコードを入力してください。</p>
<section><form id="pair"><label>本体ID<input id="device" required maxlength="64" value="stackchan-01" pattern="[a-zA-Z0-9_-]+"></label><label>あなたの名前<input id="name" required maxlength="24"></label><label>登録コード<input id="code" required maxlength="12" autocomplete="off"></label><button>登録する</button></form></section>
<section><form id="send"><label>伝えること<select id="preset"><option value="thanks">ありがとう</option><option value="rest">おつかれさま</option><option value="hello">こんにちは</option></select></label><button id="sendButton" disabled>送る</button><button type="button" id="forget">この端末の登録を忘れる</button></form><p id="status" role="status">未登録</p><ul id="messages"></ul></section>
<script>
let saved;try{saved=JSON.parse(sessionStorage.getItem('stackchan.sender')||'null')}catch{}
let pendingId, pendingPreset, busy=false;
const el=id=>document.getElementById(id); const status=text=>el('status').textContent=text;
if(saved){el('device').value=saved.deviceId;el('sendButton').disabled=false}
async function request(action,input,token){const response=await fetch('/api/inbox/'+action,{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify(input)});if(!response.ok)throw Error(response.status===401?'登録が無効です。本体でコードを発行し直してください。':response.status===429?'件数が上限です。少し待ってから試してください。':'送信できませんでした。');return response.json()}
el('pair').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;try{const deviceId=el('device').value;const result=await request('claim',{deviceId,code:el('code').value,name:el('name').value});saved={deviceId,token:result.token};sessionStorage.setItem('stackchan.sender',JSON.stringify(saved));pendingId=undefined;el('code').value='';el('sendButton').disabled=false;status('登録しました')}catch(error){status(error.message)}finally{busy=false}};
el('send').onsubmit=async event=>{event.preventDefault();if(!saved||busy)return;busy=true;el('sendButton').disabled=true;try{if(!pendingId){pendingId=crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);pendingPreset=el('preset').value}await request('send',{deviceId:saved.deviceId,id:pendingId,preset:pendingPreset},saved.token);pendingId=undefined;status('本体への配送待ちです')}catch(error){status(error.message+' 同じ内容で再試行できます。')}finally{busy=false;el('sendButton').disabled=!saved}};
el('forget').onclick=()=>{saved=undefined;pendingId=undefined;sessionStorage.removeItem('stackchan.sender');el('sendButton').disabled=true;el('messages').replaceChildren();status('この端末の登録を削除しました。本体では「登録を解除」で送信権限も取り消せます。')};
async function poll(){if(saved&&!busy&&!document.hidden){try{const result=await request('status',{deviceId:saved.deviceId},saved.token);status(result.connected?'本体に接続中':'本体は未接続');el('messages').replaceChildren(...result.entries.map(entry=>{const li=document.createElement('li');li.textContent=entry.deleted?'本体で削除済み':entry.reply?'返事: ありがとう':entry.read?'既読':'未読';return li}))}catch(error){status(error.message)}}setTimeout(poll,5000)}poll();
</script></html>`
