export const PREFERENCE_KEYS = [
  'conversation.backend',
  'conversation.autoStart',
  'gateway.endpoint',
  'gateway.deviceId',
  'gateway.clientId',
  'gateway.token',
  'gateway.microphone',
  'companion.greetingOnBoot',
  'companion.idleReactions',
  'wifi.ssid',
  'wifi.password',
  'driver.type',
  'driver.offsetPan',
  'driver.offsetTilt',
  'ui.type',
  'ui.language',
  'tts.type',
  'tts.host',
  'tts.port',
  'tts.token',
  'tts.voice',
  'tts.volume',
  'ai.token',
  'ai.context',
  'mcp.token',
] as const

export type PreferenceKey = (typeof PREFERENCE_KEYS)[number]
export type PreferenceValues = Record<PreferenceKey, string>

export const DEFAULT_PREFERENCES: PreferenceValues = {
  'conversation.backend': 'none',
  'conversation.autoStart': '0',
  'gateway.endpoint': '',
  'gateway.deviceId': 'stackchan-01',
  'gateway.clientId': 'companion',
  'gateway.token': '',
  'gateway.microphone': '0',
  'companion.greetingOnBoot': '1',
  'companion.idleReactions': '1',
  'wifi.ssid': '',
  'wifi.password': '',
  'driver.type': 'm5stackchan',
  'driver.offsetPan': '0',
  'driver.offsetTilt': '0',
  'ui.type': 'simple',
  'ui.language': 'ja',
  'tts.type': 'voicevox',
  'tts.host': '',
  'tts.port': '',
  'tts.token': '',
  'tts.voice': '',
  'tts.volume': '1',
  'ai.token': '',
  'ai.context': '',
  'mcp.token': '',
}

export const isPreferenceKey = (value: string): value is PreferenceKey =>
  (PREFERENCE_KEYS as readonly string[]).includes(value)
